spring.application.name=boot-demo-1
server.port=8080
#spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
#spring.datasource.url=${DB_URL:jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.url=jdbc:postgresql://trainingserver.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=${DB_USER:training}
spring.datasource.password=welcome@123
#spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=test

management.endpoints.web.exposure.include=*
name=shantanu