spring.application.name=boot-demo-1
server.port=8080
spring.datasource.url=jdbc:postgresql://trainingserver.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=${DB_USER:training}
spring.datasource.password=welcome@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=test

management.endpoints.web.exposure.include=*
name=shantanu